const dayObj = new Date();
const year = dayObj.getFullYear();
const month = dayObj.getMonth()+1;
const day = dayObj.getDay()+1;
const newDate = day + "/" + month + "/" + year;

const macroData = [
    {
        id:"mac1",
        year:"2022",
        month:"June",
        day:"20",
        dayOfWeek:"Wednesday",
        carbs:"75",
        protein:"185",
        fats:"110"
    },
    {
        id:"mac2",
        year:"2022",
        month:"June",
        day:"21",
        dayOfWeek:"Thursday",
        carbs:"90",
        protein:"200",
        fats:"110"
    },
    {
        id:"mac3",
        year:"2022",
        month:"June",
        day:"22",
        dayOfWeek:"Friday",
        carbs:"80",
        protein:"185",
        fats:"105"
    },
    {
        id:"mac4",
        year:"2022",
        month:"June",
        day:"23",
        dayOfWeek:"Saturday",
        carbs:"160",
        protein:"195",
        fats:"50"
    },
    {
        id:"mac5",
        year:"2022",
        month:"June",
        day:"24",
        dayOfWeek:"Sunday",
        carbs:"140",
        protein:"190",
        fats:"40"
    },
    {
        id:"mac6",
        year:"2022",
        month:"June",
        day:"25",
        dayOfWeek:"Monday",
        carbs:"60",
        protein:"185",
        fats:"50"
    },
    {
        id:"mac7",
        year:"2022",
        month:"June",
        day:"26",
        dayOfWeek:"Tuesday",
        carbs:"90",
        protein:"190",
        fats:"40"
    },
    {
        id:"mac9",
        year:"2022",
        month:"June",
        day:"27",
        dayOfWeek:"Wednesday",
        carbs:"70",
        protein:"190",
        fats:"110"
    },
    {
        id:"mac10",
        year:"2022",
        month:"June",
        day:"28",
        dayOfWeek:"Wednesday",
        carbs:"70",
        protein:"190",
        fats:"110"
    },
    {
        id:"mac11",
        year:"2022",
        month:"July",
        day:"1",
        dayOfWeek:"Wednesday",
        carbs:"70",
        protein:"230",
        fats:"110"
    },
    {
        id:"mac12",
        year:"2022",
        month:"July",
        day:"2",
        dayOfWeek:"Thursday",
        carbs:"60",
        protein:"180",
        fats:"110"
    },
    {
        id:"mac13",
        year:"2022",
        month:"July",
        day:"3",
        dayOfWeek:"Friday",
        carbs:"110",
        protein:"205",
        fats:"90"
    },
    {
        id:"mac14",
        year:"2022",
        month:"July",
        day:"4",
        dayOfWeek:"Saturday",
        carbs:"220",
        protein:"230",
        fats:"50"
    },
    {
        id:"mac15",
        year:"2022",
        month:"July",
        day:"5",
        dayOfWeek:"Sunday",
        carbs:"130",
        protein:"190",
        fats:"45"
    },
]

export default macroData;